# Generated by Django 5.2.7 on 2025-10-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Receitas',
        ),
    ]
